fixtures:
    repositories:
        stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
        staging: https://github.com/nanliu/puppet-staging.git
    symlinks:
        znapzend: "#{source_dir}"
