---
name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Create Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Activate Ruby 3.2"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Print bundle environment
        run: |
          echo ::group::bundler environment
          bundler env
          echo ::endgroup::

      - name: Build and validate module
        run: |
          bundle exec rake build validate lint check spec

      - name: Generate Changelog
        id: changelog
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          
          # Generate changelog content (basic implementation)
          echo "## Release ${VERSION}" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "### Changes" >> RELEASE_NOTES.md
          git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> RELEASE_NOTES.md || echo "- Initial release" >> RELEASE_NOTES.md

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ steps.changelog.outputs.version }}"
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pkg/igpp-znapzend-${{ steps.changelog.outputs.version }}.tar.gz
          asset_name: igpp-znapzend-${{ steps.changelog.outputs.version }}.tar.gz
          asset_content_type: application/gzip

  forge:
    name: "Deploy to Puppet Forge"
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Activate Ruby 3.2"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Deploy to Puppet Forge
        run: |
          if [ -n "${BLACKSMITH_FORGE_API_KEY}" ]; then
            echo "Deploying to Puppet Forge..."
            bundle exec rake module:push
          else
            echo "PUPPET_FORGE_API_KEY not set, skipping Forge deployment"
            exit 0
          fi
        env:
          BLACKSMITH_FORGE_URL: https://forgeapi.puppetlabs.com
          BLACKSMITH_FORGE_API_KEY: ${{ secrets.PUPPET_FORGE_API_KEY }}